ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CHECKED_IN';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TABLE "AuditLog" DROP CONSTRAINT IF EXISTS "AuditLog_userId_fkey";
ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "bookingCode" TEXT, ADD COLUMN IF NOT EXISTS "checkedInAt" TIMESTAMP(3);
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "hash" TEXT, ADD COLUMN IF NOT EXISTS "ipAddress" TEXT, ADD COLUMN IF NOT EXISTS "prevHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "failedLogins" INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS "isDecoy" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN IF NOT EXISTS "lockedUntil" TIMESTAMP(3);
CREATE UNIQUE INDEX IF NOT EXISTS "Appointment_bookingCode_key" ON "Appointment"("bookingCode");
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
